Fix/addressing major regressions (#131)
* refactor: refactored modal for manually adding profile in import page to render based on selected data type

* feat: added form UI for manually adding profile

* feat: added form validations in frontend for manually adding profile

* fix: validate function and successMsg assignment in AddProfileModal body components are now assigned inside useEffect removing unresponsiveness issue

* fix: typeerror validateFields is not a function

* fix: refactored add profile modals and flow for validation/addition of profile

* fix: add profile modal in import page resets state on close

* fix: add unit modal resets state on close

* fix: fixed accidental () in line 187 of CreateUnitModal.jsx causing infinite render

* fix: refactor editProfileModal names, AddBelbinModalBody.jsx closes on submit, updated prop drilling in Import.jsx for edit modal

* fix: manual add student used studentID instead of studentId as profile key causing deletion issues for manually added entries

* feat: EditBelbinModal.jsx implemented

* feat: all edit modals implemented

* fix: uncommented edit modal variantes in EditProfileModal.jsx